---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: sampo
  labels:
    app: sampo
  namespace: sampo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sampo
  template:
    metadata:
      labels:
        app: sampo
    spec:
      securityContext:
        runAsUser: 0
      volumes:
      - name: k8s-sampo-conf
        configMap:
          name: k8s-sampo-conf
      - name: k8s-sampo-scripts
        configMap:
          name: k8s-sampo-scripts
      containers:
      - name: sampo
        image: sampo:1.0.0
        imagePullPolicy: Never
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 1042
        volumeMounts:
        - name: k8s-sampo-conf
          mountPath: /sampo/sampo.conf
          subPath: sampo.conf
        - name: k8s-sampo-scripts
          mountPath: /sampo/scripts
